version: '3.8'

services:
  backend:
    image: charlie3379/banco-nexus-backend:latest
    env_file:
      - .env
    networks:
      - nexus_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.tier == backend

  frontend:
    image: charlie3379/banco-nexus-frontend:latest
    ports:
      - "80:80"
    networks:
      - nexus_net
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.tier == frontend

networks:
  nexus_net:
    driver: overlay